#!/bin/bash

project=npool
snapshot_dir=../snapshots/$project
flash_root=/media/CASPER
flash_dir=$flash_root/flash/projects/esbsn/$project
filename=$project\_src_$(date +%Y%m%d_%H%M%S).tar.bz2

if [ ! -d $snapshot_dir ]
then
	mkdir -p $snapshot_dir
fi

tar vjcf ../$filename -X snapshot.ignore ../$project
mv ../$filename $snapshot_dir

if [ -d $flash_root ]
then
	mkdir -p $flash_dir
	cp $snapshot_dir/$filename $flash_dir
else
	echo "$flash_root is not found"
fi
